import json

def load_data(file_path):
  """The function loads a json file with data about the animals."""
  with open(file_path, "r", encoding="utf-8") as handle:
    return json.load(handle)


def serialize_animal(animal):
    """Converts a single animal object into HTML tags."""
    output = '<li class="cards__item">'

    output += f"<div class='card__title'>{animal['name']}</div><br/>\n"

    scientific_name = animal.get("taxonomy", {}).get("scientific_name")
    if scientific_name:
        output += f"<div class='card__subtitle'>{scientific_name.upper()}</div>\n"

    output += '<div class="card__text">'
    output += '<ul>'
    characteristics = animal.get("characteristics", {})
    if "diet" in characteristics:
        output += f"<li><strong>Diet:</strong> {characteristics['diet']}</li>\n"
    if "prey" in characteristics:
        output += f"<li><strong>Prey:</strong> {characteristics['prey']}</li>\n"
    if "predators" in characteristics:
        output += f"<li><strong>Predators:</strong> {characteristics['predators']}</li>\n"
    if "type" in characteristics:
        output += f"<li><strong>Type:</strong> {characteristics['type']}</li>\n"
    locations = animal.get("locations", [])
    if locations:
        output += f"<li><strong>Location:</strong> {locations[0]}</li>\n"
        output +=  "</ul></div></li>"

    return output


def print_animals_info(animals):
    """Iterates over all animals and generates the full HTML list."""
    output = ''
    for animal in animals:
        output += serialize_animal(animal)
    return output


def read_html_template(file_path):
    """The function opens and reads the given html template with the placeholder string."""
    with open(file_path, "r", encoding="utf-8") as template:
        return template.read()


def create_animals_html(template, output_path, animals_info):
    """This function takes the template string, replaces the placeholder with
    the string generated by print_animals_info and saves result as animals.html  """
    new_html = template.replace("__REPLACE_ANIMALS_INFO__", animals_info)
    with open(output_path, "w", encoding="utf-8") as animals_html_file:
        animals_html_file.write(new_html)


def main():
    """Here is the main function that coordinates data collection, manipulation and output."""
    animals_data = load_data('animals_data.json')
    animals_info = print_animals_info(animals_data)
    template = read_html_template ("animals_template.html")
    create_animals_html(template, "animals.html", animals_info)

if __name__ == "__main__":
    main()
